<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;

class AkunSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = [
            [
              'npp'=>'admin',
              'name'=>'admin',
              'level'=>'admin',
              'status' => 'admin',
              'jabatan' => 'admin',
              'password'=> bcrypt('123456'),
            ],
            [
               'npp'=>'1',
               'name'=>'farhan',
               'level'=>'user',
               'status' => 'PNS',
               'jabatan' => 'Guru Kelas',
               'nama_lengkap' => 'Ilham1',
               'tanggal_masuk' => '12-12-2022',
                'nama_sekolah' => 'SMK Wikrama',
                'npsn'=> '1190',
                'nik'=>'1190',
                'jk'=> 'Laki - Laki',
                'tgl_lahir' => '17-12-2222',
                'ttl' => 'bandung',
                'nama_ibu' => 'susi',
                'alamat_lengkap' => 'bogor',
                'lintang'=>'22',
                'bujur'=> '89',
                'kk' => '18384',
                'kode_pos' => '97487',
                'agama' => 'Islam',
                'npwp' => '1932',
                'nama_pajak' => 'farhan',
                'kewarganegaraan' => 'Indonesia(WNI)',
                'nama_negara' => '',
                'kawin' => 'Belum Kawin',
                'nama_pasangan' => '',
                'nip_pasangan' => '',
                'pekerjaan_pasangan' => '',
                'niy' => '89',
                'nuptk' => '88',
                'sumber_gaji' => 'SMK Wikrama',
                'kartu_pegawai' => '7886',
                'kartu_pasangan' => '',
                'nomor_rumah' => '629328975934',
                'nomor_hp' => '235235',
                'email' => 'kitabisa@gmail.com',
                'keluar' => '',
                'tanggal_keluar' => '',
               'password'=> bcrypt('123456'),
            ],
            [
                'npp'=>'2',
                'name'=>'kevin',
                'level'=>'user',
                'status' => 'PNS',
                'nama_lengkap' => 'Ilham2',
                'jabatan' => 'Guru Kelas',
                'tanggal_masuk' => '12-12-2022',
                 'nama_sekolah' => 'SMK Wikrama',
                 'npsn'=> '1190',
                 'alamat_sekolah' => 'Tajur',
                 'nik'=>'1190',
                 'jk'=> 'Laki - Laki',
                 'tgl_lahir' => '17-12-2222',
                 'ttl' => 'bandung',
                 'nama_ibu' => 'ninda',
                 'alamat_lengkap' => 'bogor',
                 'lintang'=>'22',
                 'bujur'=> '89',
                 'kk' => '18384',
                 'kode_pos' => '97487',
                 'agama' => 'Islam',
                 'npwp' => '1932',
                 'nama_pajak' => 'farhan',
                 'kewarganegaraan' => 'Asing(WNA)',
                 'nama_negara' => 'India',
                 'kawin' => 'Kawin',
                 'nama_pasangan' => 'susi',
                 'nip_pasangan' => '232',
                 'pekerjaan_pasangan' => 'Tidak Bekerja',
                 'niy' => '89',
                 'nuptk' => '88',
                 'sumber_gaji' => 'SMK Wikrama',
                 'kartu_pegawai' => '7886',
                 'kartu_pasangan' => '8998',
                 'nomor_rumah' => '629328975934',
                 'nomor_hp' => '235235',
                 'email' => 'kitabisa@gmail.com',
                 'keluar' => '',
                 'tanggal_keluar' => '',
               'password'=> bcrypt('123456'),
            ],
            [
                'npp'=>'3',
                'name'=>'jeson',
                'level'=>'user',
                'status' => 'PNS',
                'nama_lengkap' => 'Ilham3',
                'jabatan' => 'Guru Kelas',
                'tanggal_masuk' => '12-12-2022',
                 'nama_sekolah' => 'SMK Wikrama',
                 'npsn'=> '1190',
                 'alamat_sekolah' => 'Tajur',
                 'nik'=>'1190',
                 'jk'=> 'Laki - Laki',
                 'tgl_lahir' => '17-12-2222',
                 'ttl' => 'bandung',
                 'nama_ibu' => 'susi',
                 'alamat_lengkap' => 'bogor',
                 'lintang'=>'22',
                 'bujur'=> '89',
                 'kk' => '18384',
                 'kode_pos' => '97487',
                 'agama' => 'Islam',
                 'npwp' => '1932',
                 'nama_pajak' => 'JESON',
                 'kewarganegaraan' => 'Indonesia(WNI)',
                 'nama_negara' => '',
                 'kawin' => 'Kawin',
                 'nama_pasangan' => 'sfad',
                 'nip_pasangan' => '2322',
                 'pekerjaan_pasangan' => 'Tidak Berkerja',
                 'niy' => '89',
                 'nuptk' => '88',
                 'sumber_gaji' => 'SMK Wikrama',
                 'kartu_pegawai' => '7886',
                 'kartu_pasangan' => '76887',
                 'nomor_rumah' => '629328975934',
                 'nomor_hp' => '235235',
                 'email' => 'kitabisa@gmail.com',
                 'keluar' => 'Mutasi',
                 'tanggal_keluar' => '19-12-2020',
               'password'=> bcrypt('123456'),
            ],
        ];

        foreach ($user as $key => $value) {
            User::create($value);
        }
    }
}
